@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

scale 0.8

class Person
class Personalausweis

' Relations:
'   a) "- - - ->"  = dependency
'   b) "------->"  = association

Person   "1 "   --d->   "1 "   Personalausweis : hat\n(//genau einen//)



@enduml