include::../../docs/settings.adoc[]
include::module-settings.adoc[]
:author: Thorsten Eckstein

// table of contents
:toc:

////
  Folgendes wird in "course-structure.adoc"
  aus jedem Modul zusammengeführt:

tag::content[]
----
1. Logische Operatoren
----
end::content[]
////


== Logische Operatoren

Die *logischen Operatoren* dienen zum Vergleich von Wahrheitswerten unter Nutzung des primitiven Datentyps

 boolean bzw. Boolean

und werden u.a. für *Bedingungen von Kontrollstrukturen* (vgl. vorheriges Thema), etwa für `if` Anweisungen oder Schleifen verwendet.

Durch logische Operatoren können einzelne Wahrheitswerte verändert bzw. negiert und auch verknüpft werden.
Egal wie, das Ergebnis der Verarbeitung von logischen Operatoren ist immer ein Wahrheitswert, also wieder ein `boolean`.

*Ausdruck*:

 boolean b = operand1 operator operand2

also z.B. der Test, ob eine Zahl eine einstellige Ganzzahl ist:

 boolean b =  i >= 1  &&  i < 10
 boolean b = (i >= 1) && (i < 10) // für bessere Verständlichkeit

Es gibt verschiedene *logische Operatoren*:

TIP: Vgl. Testklasse: `/module-operators/src/test/java/de/dhbw/operators/OperatorDemoTests.java`

[cols="^1m,9e,1l"]
|===
| Operator | Erläuterung/Bedeutung | Testmethode

| &&
| Doppeltes UND ist eine logische UND-Verknüpfung, bei der wir nur ein wahres Ergebnis erhalten, wenn beide Operanden wahr sind. Ist an dieser Stelle bereits der erste Operand falsch (false) so wird der zweite Operand nicht mehr ausgewertet, da false und irgendwas bei einer logischen UND-Verknüpfung als Resultat immer false hat.
| testOperator1()

| &
| Einfaches UND ist eine logische UND-Verknüpfung. Bei dieser logischen UND-Verknüpfung werden beide Operanden ausgewertet.
| testOperator2()

| \|\|
| Doppeltes ODER ist eine logische ODER-Verknüpfung, bei der wir nur ein falsches Ergebnis erhalten, wenn beide Operanden falsch sind. Ist an dieser Stelle bereits der erste Operand wahr (true) so wird der zweite Operand nicht mehr ausgewertet, da true und irgendwas bei einer logischen ODER-Verknüpfung als Resultat immer true hat.
| testOperator3()

| \|
| Einfaches ODER ist eine logische ODER-Verknüpfung. Bei dieser logischen ODER-Verknüpfung werden beide Operanden ausgewertet.
| testOperator4()

| !
| Das Ausrufezeichen ist der Negierungsoperator in der bool'schen Logik. Aus wahr (true) wird falsch (false) und umgekehrt.
| testOperator5()

| ^
| Das "Dach" wird als Exklusiv-Oder bezeichnet. Entweder der erste oder der zweite Ausdruck muss wahr sein. Es dürfen aber nicht beide Ausdrücke gleich sein, damit das Ergebnis wahr wird.
| testOperator6()
|===


=== Demonstrationen

Tests zur *Demonstration*:

[subs=normal]
 {mod-ref-test}/operators/OperatorDemoTests.java


=== Übungen

[subs=normal]
 {mod-ref-test}/operators/OperatorExerciseTests.java

[[enums-exercise-1]]
*Übung 1:*

Werte den folgenden Ausdruck aus:

 boolean result = one && two | three;

a) Ermittle das Ergebnis mit `System.out.println(...)` oder `assertEquals(...)`

b) Erläutere die logischen Operatoren


[[enums-exercise-2]]
*Übung 2:*

Erstelle eine `boolean` Variable, _negiere_ diese und teste das Ergebnis in einem Unit-Test.


