include::../../docs/settings.adoc[]
include::module-settings.adoc[]
:author: Thorsten Eckstein

// table of contents
:toc:

////
  Folgendes wird in "course-structure.adoc"
  aus jedem Modul zusammengeführt:

tag::content[]
----
 1. Hinweis zum "Ausprobieren & Experimentieren"
----
end::content[]
////

== Hinweis zum "Ausprobieren & Experimentieren"

Dieses Modul dient einfach als *Übungsmodul*, damit man die Grundlagen der Javaprogrammierung einfach mal und unabhängig von den anderen Inhalten ausprobieren kann.

Alle wesentlichen Aspekte werden zwar im Lauf der Lehrveranstaltung im Detail besprochen, dennoch kann es hilfreich sein, hier unabhängig nochmal ein paar Dinge für sich selber zu testen und ein _"Gefühl"_ für die Sprache zu bekommen.

Aus diesem Grund enthält dieses Modul selbst _keinen eigentlichen Inhalt_ oder Theorie. Die theoretischen & praktischen Grundlagen sind Teil der anderen Module, die nach und nach vertieft werden.

Damit man möglichst einfach beginnen kann, gibt es eine vorbereitete *Test-Klasse* hier:

[subs=normal]
 module-experiments/{mod-ref-test}/exercise/BasicsExerciseTest.java

Sie enthält bereits einen Test, den man umsetzen kann, es können aber natürlich beliebige weitere zu der Klasse hinzugefügt werden. Das geht einfach, indem man einfach weitere Testmethoden hinzufügt. Hier die Vorlagen zum Kopieren:

[source, java]
----
@Test
@DisplayName(
"""
  <Beschreibung, was in diesem Test getestet werden soll>

  HINWEIS: Der Methodenname muss eindeutig sein, hier 'exercise1()', bei
           weiteren Tests kann man dann einfach die Nummer hochzählen,
           der nächste Test wäre also 'exercise2()' oder man nennt die
           Methode danach, was durch sie getestet werden soll, z.B. so
           etwas wie 'canCreateInstanceOfClass()'
""")
public void exercise1() {
    // given

    // when

    // then
}
----

Wenn man im Rahmen dieses "Ausprobierens" Klassen angelegt werden, so sollen diese in den *"echten" Sourcecode-Packages* gespeichert werden, und zwar hier:

[subs=normal]
 module-experiments/{mod-ref-src}/exercise/*

Die "echten" Klassen, die im Test genutzt werden sollen, werden automatisch erkannt, wenn die obige Struktur genutzt wird. Wenn nicht, dann bitte folgenden Hinweis beachten.

CAUTION: _Achtung: Wenn man eigene Pakete/Verzeichnisse für neue Klassen anlegt, so müssen diese ggf. importiert werden. Mehr dazu siehe ->_
`/module-classes/docs/classes.adoc` im Abschnitt "Importierung".
