@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

scale 1.0

class ConcreteSuperClass {}
class "       SubClass1        " as SubClass1

abstract class AbstractSuperClass {}
class "       SubClass2        " as SubClass2

ConcreteSuperClass <|-- SubClass1    : \tinherits (extends)

AbstractSuperClass <|-- SubClass2


@enduml