include::settings.adoc[]

:toc:
:sectnums!:

= Programmierung II mit Java

:show-scheduled-course-days: false
ifeval::[{show-scheduled-course-days} == true]
include::includes/course-day-schedules.adoc[]
endif::[]

== Tag 1 - Willkommen, Setup & primitive Datentypen

[subs=normal]
 [*Di., 18.02.2025*, 13:00 - 16:00, 180min] [red]#"Course Day 1"#

*Inhalt*:

[source]
----
  1) Willkommen
  2) Organisation
  3) Fachlicher Schwerpunkt
  4) Technical Setup
  5) Tools: Maven & Projektstruktur
  6) Pause
  7) Datentypen in Java
  8) Typumwandlung (Casting)
  9) Test-Driven-Development (TDD)
  10) Demo zu Typumwandlung von primitiven Datentypen
  11) Übungen zu Typumwandlung von primitiven Datentypen
  12) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-intro/docs/intro.adoc[module-intro]
. {icon-module} link:../module-tools-n-help/docs/tools-and-help.adoc[module-tools-n-help]
. {icon-module} link:../module-datatypes/docs/datatypes.adoc[module-datatypes]

*Ergänzend*:

Das folgende Modul dient einfach als *Übungs- oder auch als Experimentiermodul*, in dem jeder für sich die Grundlagen der Javaprogrammierung einfach (noch) mal, und unabhängig von den übrigen Inhalten, ausprobieren kann.

. {icon-exercise} link:../module-basics/docs/basics.adoc[module-basics]


== Tag 2 - Klassen, Vererbung & Polymorphismus

[subs=normal]
 [*Di., 25.02.2025*, 13:00 - 16:00, 180min] [red]#"Course Day 2"#

*Inhalt*:

[source]
----
  1) Update Project (git pull)
  2) Klassen & Instanzen
  3) Demo zu Klassen & Instanzen
  4) Organisation & Nutzung von Java Klassen (Packages)
  5) Übungen zu Klassen & Instanzen
  6) Vererbung (Inheritance)
  7) Demo zum Thema Vererbung
  8) Übungen zur Vererbung
  9) Pause
  10) Polymorphismus
  11) Demo Polymorphismus
  12) Override & Overload
  13) Demo zu Überladen & Übersteuern
----

*Zugehörige Module*:

. {icon-module} link:../module-classes/docs/classes.adoc[module-classes]


== Tag 3 - Interfaces, Abstraktionen & Typumwandlung komplexer Datentypen

[subs=normal]
 [*Mi., 05.03.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 3"#

*Inhalt*:

[source]
----
  1) Update Project (git pull)
  2) Kurze Wiederholung Typumwandlung (Casting)
  3) Demo zu Typumwandlung von komplexer Datentypen (Klassen)
  4) Übungen zu Typumwandlung von komplexen Datentypen (Klassen)
  5) Sichtbarkeiten & Scopes
  6) Demo zu Sichtbarkeiten
  7) Pause
  8) Interfaces
  9) Interfaces Demo
  10) Interfaces Exercise
  11) Abstrakte Klassen
  12) Demo abstrakte Klassen
  13) Übung zu abstrakten Klassen
  14) Tools: Hilfreiches im Umgang mit IntelliJ
  15) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-datatypes/docs/datatypes.adoc[module-datatypes]
. {icon-module} link:../module-interfaces/docs/interfaces.adoc[module-interfaces]
. {icon-module} link:../module-tools-n-help/docs/tools-and-help.adoc[module-tools-n-help]


== Tag 4 - Sichtbarkeiten, Kontrollstrukturen & Collections API

[subs=normal]
 [*Mi., 12.03.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 4"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Sichtbarkeiten & Scopes
  4) Demo zu Sichtbarkeiten
  5) Kontrollstrukturen
  6) Pause
  7) Demo zu Kontrollstrukturen
  8) Übung zu Kontrollstrukturen
  9) Java Collections API
  10) Demo zur Collections API
  11) Übungen Collections API
  12) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-visibility/docs/visibility.adoc[module-visibility]
. {icon-module} link:../module-loops/docs/loops.adoc[module-loops]
. {icon-module} link:../module-collections/docs/collections.adoc[module-collections]


== Tag 5 - Operatoren, Assoziationen & Java Generics

[subs=normal]
 [*Di., 18.03.2025*, 13:00 - 16:00, 180min] [red]#"Course Day 5"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Logische Operatoren
  4) Demo zu Operatoren
  5) Übungen zu Operatoren
  6) Assoziationen zwischen Klassen
  7) Pause
  8) Demo zu Assoziationen
  9) Übungen zu Assoziationen
  10) Java Generics (Einführung)
  11) Generics Demo und/oder Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-operators/docs/operators.adoc[module-operators]
. {icon-module} link:../module-associations/docs/associations.adoc[module-associations]
. {icon-module} link:../module-generics/docs/generics.adoc[module-generics (Einf.)]


== Tag 6 - Java Generics (Forts.), funktionale Programmierung

[subs=normal]
 [*Mi., 26.03.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 6"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Generics (Wiederholung & Fortsetzung)
  4) Demos zu Java Generics
  5) Übungen zu Java Generics
  6) Pause
  7) Funktionale Programmierung in Java
  8) Demos zu funktionaler Programmierung
  9) Übungen zu funktionaler Programmierung
  10) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-generics/docs/generics.adoc[module-generics (Forts.)]
. {icon-module} link:../module-funcprogramming/docs/functional-programming.adoc[module-funcprogramming]


== Tag 7 - Ausnahmen, Fehlerbehandlung, statische Elemente & Enums

[subs=normal]
 [*Mi., 02.04.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 7"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Exceptions & Exception Handling
  4) Demo zu Exceptions
  5) Übungen zu Exceptions
  6) Pause
  7) Statische Elemente
  8) Demo zu statischen Elementen
  9) Enums
  10) Demo zu Enums
  11) Übungen zu Enums
----

*Zugehörige Module*:

. {icon-module} link:../module-exceptions/docs/exception-handling.adoc[module-exceptions]
. {icon-module} link:../module-statics/docs/statics.adoc[module-statics]
. {icon-module} link:../module-enums/docs/enums.adoc[module-enums]


== Tag 8 - Referenzsemantik, Object-Vertrag & Records

[subs=normal]
 [*Mi., 09.04.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 8"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Referenzsemantik
  4) Demo Referenzsemantik
  5) Der Objektvertrag
  6) Demos zum Objektvertrag
  7) Pause
  8) Übungen zum Objektvertrag
  9) Java Records
  10) Demo zu Java Records
  11) Code-Qualität (Clean Code)
  12) Prüfungsvorbereitung oder Ausgabe Übungsklausur (Erläuterungen)
----

*Zugehörige Module*:

. {icon-module} link:../module-semantics/docs/reference-semantics.adoc[module-semantics]
. {icon-module} link:../module-object-contract/docs/object-contract.adoc[module-object-contract]
. {icon-module} link:../module-records/docs/records.adoc[module-records]
. {icon-module} link:../module-clean-code/docs/clean-code.adoc[module-clean-code]


== Tag 9 - Prüfungsvorbereitung

[subs=normal]
 [*Mi., 16.04.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 9"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Prüfungsvorbereitung I: Fragen, Aufgaben, Demos, Wiederholungen
  4) Pause
  5) Prüfungsvorbereitung II: Fragen, Aufgaben, Demos, Wiederholungen
----

*Mögliche Inhalte zur Prüfungsvorbereitung*:

[subs=normal]
----
- Szenarien & Modelle (vorbereitet)
- Programmieraufgaben
- Quizfragen
- Themen im "Schnelldurchlauf"
- Organisation der Prüfung
- Zeit für Fragen
----

*Zugehörige Module*:

. {icon-module} link:../module-clean-code/docs/clean-code.adoc[module-clean-code]
. {icon-module} link:../exam-preparation/docs/exam-preparation.adoc[exam-preparation]


== (Tag 10+) Semesterabschlussprüfungen

Die Ausgestaltung und der Modus der Prüfungen wird derzeit festgelegt.

////
Es gibt aber folgende *Idee*. Die *Prüfung* besteht insgesamt aus zwei Teilen:

[subs=normal]
 *Dauer*          : 1h
 *Kandidat:Innen* : 3er Gruppen

[arabic]
. Prüfung der *Programmierkenntnisse*, entweder ...
.. als 3-4er Gruppe am vorbereiteten Rechner gemeinsam & live Progemmieraufgaben lösen, mit Unit-Tests und Klassen in /src Paketen, oder ...
.. manuell schriftlich auf Papier, individuell
. Prüfung des *Grundverständnisses*: vorbereiteter Use-Case, konzeptionell mündliches Gespräch, Gruppenarbeit an der Tafel, Fragen und Antworten
////


== Optionale Themen

=== Software Patterns

include::../module-patterns/docs/patterns.adoc[tag="content"]

&rarr; {icon-module} link:../module-patterns/docs/patterns.adoc[module-patterns]


=== Datenbankprogrammierung mit Java

include::../module-databases/docs/databases.adoc[tag="content"]

&rarr; {icon-module} link:../module-databases/docs/databases.adoc[module-databases]


=== Parallele Programmierung mit Threads

include::../module-threads/docs/threads.adoc[tag="content"]

&rarr; {icon-module} link:../module-threads/docs/threads.adoc[module-threads]


=== Integration von Software/-komponenten

include::../module-integration/docs/integration.adoc[tag="content"]

&rarr; {icon-module} link:../module-integration/docs/integration.adoc[module-integration]


=== Javadoc

include::../module-javadoc/docs/javadoc.adoc[tag="content"]

&rarr; {icon-module} link:../module-javadoc/docs/javadoc.adoc[module-javadoc]

