include::settings.adoc[]

:toc:
:sectnums!:

= Programmierung II mit Java

:show-scheduled-course-days: false
ifeval::[{show-scheduled-course-days} == true]
include::includes/course-day-schedules.adoc[]
endif::[]

== Tag 1 - Setup, Java Basics & primitive Datentypen

[subs=normal]
 [*??., dd.mm.yyyy*, hh:mm - hh:mm, 180min] [red]#"Course Day 1"#

*Inhalt*:

[source]
----
1)  "Willkommen"
2)  "Organisation"
3)  "Technical Setup"
4)  "Tools: IntelliJ IDE"
5)  "Tools: Maven & Projektstruktur"
6)  "Fachlicher Schwerpunkt"
7)  "Pause"
8)  "Java Basics"
9)  "Datentypen I: Primitive Datentypen"
10) "Typumwandlung (Casting)"
11) "Demo Datentypen I: Umwandlung primitiver Datentypen"
12) "Übung Datentypen I: Umwandlung primitiver Datentypen"
13) "Lösungsbesprechung"
----

*Zugehörige Module*:

. {icon-module} link:../module-intro/docs/intro.adoc[module-intro]
. {icon-module} link:../module-tools-n-help/docs/tools-and-help.adoc[module-tools-n-help]
. {icon-module} link:../module-basics/docs/basics.adoc[module-basics]
. {icon-module} link:../module-datatypes/docs/datatypes.adoc[module-datatypes] (Teil I)

*Ergänzend*:

Das folgende Modul dient einfach als *Übungs- oder auch als Experimentiermodul*, in dem jeder für sich die Grundlagen der Javaprogrammierung einfach (noch) mal, und unabhängig von den übrigen Inhalten, ausprobieren kann.

. {icon-exercise} link:../module-experiments/docs/experiments.adoc[module-experiments]


== Tag 2 - Klassen & Instanzen, Vererbung

[subs=normal]
 [*??., dd.mm.yyyy*, hh:mm - hh:mm, 180min] [red]#"Course Day 2"#

*Inhalt*:

[source]
----
1)  "Update Project (git pull)"
2)  "Test-Driven-Development (TDD)"
3)  "Klassen & Instanzen"
4)  "Organisation & Nutzung von Java Klassen (Packages)"
5)  "Demo zu Klassen & Instanzen"
6)  "Übungen zu Klassen & Instanzen"
7)  "Erstellung einer Java Klasse mithilfe von KI"
8)  "Pause"
9)  "Vererbung (ohne Abstraktionen)"
10) "Demo zum Thema Vererbung"
11) "Übungen zur Vererbung"
12) "Datentypen II: Die Klasse als komplexer Datentyp"
13) "Demo: Typumwandlung von Klassen"
14) "Pufferzeit"
----

*Zugehörige Module*:

. {icon-module} link:../module-tools-n-help/docs/tools-and-help.adoc[module-tools-n-help] (TDD)
. {icon-module} link:../module-classes/docs/classes.adoc[module-classes]
. {icon-module} link:../module-datatypes/docs/datatypes.adoc[module-datatypes] (Teil II)


== Tag 3 - Typumwandlung von Klassen, Sichtbarkeit & Interfaces

[subs=normal]
 [*??., dd.mm.yyyy*, hh:mm - hh:mm, 180min] [red]#"Course Day 3"#

*Inhalt*:

[source]
----
1)  Update Project (git pull)"
2)  "Sichtbarkeiten & Scopes"
3)  "Demo zu Sichtbarkeiten"
4)  "Kombinationsübungen: Klassen & Sichtbarkeiten"
5)  "Interfaces"
6)  "Interfaces Demo"
7)  "Pause"
8)  "Interfaces Exercise"
9)  "Abstrakte Klassen"
10  "Demo abstrakte Klassen"
11  "Übung zu abstrakten Klassen"
12  "Erstellung einer Hierarchie: Klasse erbt von abstrakter Klasse implementiert Interface mithilfe von KI"
13) "Pufferzeit"
----

*Zugehörige Module*:

. {icon-module} link:../module-visibility/docs/visibility.adoc[module-visibility]
. {icon-module} link:../module-interfaces/docs/interfaces.adoc[module-interfaces]


== Tag 4 - Operatoren, Kontrollstrukturen & Collections API

[subs=normal]
 [*Mi., 12.03.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 4"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Logische Operatoren
  4) Demo zu Operatoren
  5) Übungen zu Operatoren
  6) Kontrollstrukturen
  7) Pause
  8) Demo zu Kontrollstrukturen
  9) Übung zu Kontrollstrukturen
  10) Java Collections API
  11) Demo zur Collections API
  12) Übungen Collections API
----

*Zugehörige Module*:

. {icon-module} link:../module-operators/docs/operators.adoc[module-operators]
. {icon-module} link:../module-loops/docs/loops.adoc[module-loops]
. {icon-module} link:../module-collections/docs/collections.adoc[module-collections]


== Tag 5 - Assoziationen & Java Generics

[subs=normal]
 [*Di., 18.03.2025*, 13:30 - 16:00, 180min] [red]#"Course Day 5"#

CAUTION: [red]#_!!! Verkürzung der LV um eine halbe Stunde (13:30 - 16:00)!!!_#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Assoziationen zwischen Klassen
  4) Pause
  5) Demo zu Assoziationen
  6) Übungen zu Assoziationen
  7) Java Generics
  8) Demos zu Java Generics
  9) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-associations/docs/associations.adoc[module-associations]
. {icon-module} link:../module-generics/docs/generics.adoc[module-generics (Einf.)]


== Tag 6 - Java Generics, funktionale Programmierung

[subs=normal]
 [*Mi., 26.03.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 6"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Generics (kurze Wiederholung)
  4) Demos zu Java Generics
  5) Übungen zu Java Generics
  6) Pause
  7) Funktionale Programmierung in Java
  8) Demos zu funktionaler Programmierung
  9) Übungen zu funktionaler Programmierung
  10) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-generics/docs/generics.adoc[module-generics] (Forts.)
. {icon-module} link:../module-funcprogramming/docs/functional-programming.adoc[module-funcprogramming]


== Tag 7 - Ausnahmen, Fehlerbehandlung, statische Elemente & Enums

[subs=normal]
 [*Mi., 02.04.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 7"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Funktionale Programmierung in Java (Wiederh.)
  4) Übungen zu funktionaler Programmierung
  5) Exceptions & Exception Handling
  6) Demo zu Exceptions
  7) Pause
  8) Übungen zu Exceptions
  9) Statische Elemente
  10) Demo zu statischen Elementen
  11) Enums
  12) Demo zu Enums
  13) (Optional) Übungen zu Enums
----

*Zugehörige Module*:

. {icon-module} link:../module-funcprogramming/docs/functional-programming.adoc[module-funcprogramming]
. {icon-module} link:../module-exceptions/docs/exception-handling.adoc[module-exceptions]
. {icon-module} link:../module-statics/docs/statics.adoc[module-statics]
. {icon-module} link:../module-enums/docs/enums.adoc[module-enums]


== Tag 8 - Referenzsemantik, Object-Vertrag & Records

[subs=normal]
 [*Mi., 09.04.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 8"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Der Objektvertrag
  4) Demos zum Objektvertrag
  5) Übungen zum Objektvertrag
  6) Referenzsemantik
  7) Pause
  8) Demo Referenzsemantik
  9) Java Records
  10) Demo zu Java Records
  11) Clean Code
  12) Pufferzeit
----

*Zugehörige Module*:

. {icon-module} link:../module-object-contract/docs/object-contract.adoc[module-object-contract]
. {icon-module} link:../module-semantics/docs/reference-semantics.adoc[module-semantics]
. {icon-module} link:../module-records/docs/records.adoc[module-records]
. {icon-module} link:../module-clean-code/docs/clean-code.adoc[module-clean-code]


== Tag 9 - Prüfungsvorbereitung

[subs=normal]
 [*Mi., 16.04.2025*, 09:15 - 12:15, 180min] [red]#"Course Day 9"#

*Inhalt*:

[source]
----
  1) Come in, sit down and relax
  2) Project Update
  3) Prüfungsvorbereitung I: Fragen, Aufgaben, Demos, Wiederholungen
  4) Pause
  5) Prüfungsvorbereitung II: Fragen, Aufgaben, Demos, Wiederholungen
----

*Mögliche Inhalte zur Prüfungsvorbereitung*:

[subs=normal]
----
- Szenarien & Modelle (vorbereitet)
- Programmieraufgaben
- Quizfragen
- Themen im "Schnelldurchlauf"
- Organisation der Prüfung
- Zeit für Fragen
----

*Zugehörige Module*:

. {icon-module} link:../module-clean-code/docs/clean-code.adoc[module-clean-code]
. {icon-module} link:../exam-preparation/docs/exam-preparation.adoc[exam-preparation]


== (Tag 10+) Semesterabschlussprüfungen

Die Ausgestaltung und der Modus der Prüfungen wird derzeit festgelegt.

////
Es gibt aber folgende *Idee*. Die *Prüfung* besteht insgesamt aus zwei Teilen:

[subs=normal]
 *Dauer*          : 1h
 *Kandidat:Innen* : 3er Gruppen

[arabic]
. Prüfung der *Programmierkenntnisse*, entweder ...
.. als 3-4er Gruppe am vorbereiteten Rechner gemeinsam & live Progemmieraufgaben lösen, mit Unit-Tests und Klassen in /src Paketen, oder ...
.. manuell schriftlich auf Papier, individuell
. Prüfung des *Grundverständnisses*: vorbereiteter Use-Case, konzeptionell mündliches Gespräch, Gruppenarbeit an der Tafel, Fragen und Antworten
////


== Optionale Themen

=== Software Patterns

include::../module-patterns/docs/patterns.adoc[tag="content"]

&rarr; {icon-module} link:../module-patterns/docs/patterns.adoc[module-patterns]


=== Datenbankprogrammierung mit Java

include::../module-databases/docs/databases.adoc[tag="content"]

&rarr; {icon-module} link:../module-databases/docs/databases.adoc[module-databases]


=== Parallele Programmierung mit Threads

include::../module-threads/docs/threads.adoc[tag="content"]

&rarr; {icon-module} link:../module-threads/docs/threads.adoc[module-threads]


=== Integration von Software/-komponenten

include::../module-integration/docs/integration.adoc[tag="content"]

&rarr; {icon-module} link:../module-integration/docs/integration.adoc[module-integration]


=== Javadoc

include::../module-javadoc/docs/javadoc.adoc[tag="content"]

&rarr; {icon-module} link:../module-javadoc/docs/javadoc.adoc[module-javadoc]

